// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kkshqfoeqqllcxkvfozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc2hxZm9lcXFsbGN4a3Zmb3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzgwMjUsImV4cCI6MjA3NjAxNDAyNX0.0yYzhWU6XVra_YUGv1vTbRr9Ec0dHHDqUyuMsVJgliw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);